spring:
  application:
    name: scms-admin

  sql:
    init:
      mode: never

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.hong.scms.admin
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    "[org.mybatis]": DEBUG
    "[java.sql]": DEBUG
    "[jdbc.sqlonly]": DEBUG